# Generated by Django 4.2.7 on 2025-12-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConversationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_message", models.TextField()),
                ("bot_response", models.TextField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name_plural": "Conversation Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RealEstateData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("price_trend", models.JSONField(default=dict)),
                ("demand_score", models.FloatField(default=0.0)),
                (
                    "average_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("property_count", models.IntegerField(default=0)),
                ("analysis_summary", models.TextField(blank=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Real Estate Data",
                "ordering": ["-last_updated"],
            },
        ),
        migrations.CreateModel(
            name="UserQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField()),
                (
                    "query_type",
                    models.CharField(
                        choices=[
                            ("analysis", "Location Analysis"),
                            ("trend", "Trend Analysis"),
                            ("comparison", "Location Comparison"),
                            ("general", "General Question"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("response_time", models.FloatField(default=0.0)),
                ("was_helpful", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["location", "-created_at"],
                        name="chatbot_use_locatio_8bbb45_idx",
                    ),
                    models.Index(
                        fields=["query_type", "-created_at"],
                        name="chatbot_use_query_t_d7a20e_idx",
                    ),
                ],
            },
        ),
    ]
