# Generated by Django 4.2.7 on 2025-12-01 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                ("file_name", models.CharField(max_length=255)),
                ("file_data", models.JSONField()),
                ("columns", models.JSONField()),
                ("row_count", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="conversationhistory",
            name="chart_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userquery",
            name="query_type",
            field=models.CharField(
                choices=[
                    ("analysis", "Location Analysis"),
                    ("trend", "Trend Analysis"),
                    ("comparison", "Location Comparison"),
                    ("filter", "Data Filter"),
                    ("general", "General Question"),
                ],
                default="general",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="FilteredResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_id", models.CharField(db_index=True, max_length=100)),
                ("filter_criteria", models.JSONField()),
                ("filtered_data", models.JSONField()),
                ("row_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "data_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot.dataupload",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dataupload",
            index=models.Index(
                fields=["session_id", "-uploaded_at"],
                name="chatbot_dat_session_b3f96d_idx",
            ),
        ),
        migrations.AddField(
            model_name="conversationhistory",
            name="data_upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chatbot.dataupload",
            ),
        ),
        migrations.AddField(
            model_name="conversationhistory",
            name="filtered_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chatbot.filteredresult",
            ),
        ),
    ]
